### ISSUE TITLE
Create a list and choose random token.

### ISSUE THREAD

**Issue by Fawn77** [es3n1n/re-unplayplay#8]
So, I've seen that a token used publicly getting revoked in ±3 days. So I came here and tell an idea. 

What if you create a list contains some playplay tokens and randomize them each script runs?

E.g.:

play_token = ["token1", "token2", "token3", etc.]

randomize_token = random.choice(play_token)

So that, every selected token is randomized, right? Guess thats helping tokens live longer cause people will use different token each script runs.

**Comment by es3n1n** [comment]
Hello,
I don't really think that it matters much since I am pretty sure that these tokens are getting banned manually. If I add three of them, they will just ban all three tokens instead of just one.

**Comment by SuisChan** [comment]
> play_token = ["token1", "token2", "token3", etc.]

For each token you need to get the decryptor code, and that takes time



> Guess thats helping tokens live longer cause people will use different token each script runs.

No, they will just ban all tokens at once

The way to avoid getting token banned is to use a private version and not disclose it 🤷‍♂️

**Comment by Fawn77** [comment]
Aight I'll see, thanks for confirming. Nice work by the way!
